### ISSUE TITLE
Configurable token size

### ISSUE THREAD

**Issue by chrysn** [embassy-rs/critical-section#8]
This seems reasonably well implementable on RIOT-OS, but the token size is too small (RIOT's irq_disable / restore lugs around a c_int).

I suggest to have the actual type (which may be type aliased for convenience) depend on a crate feature.

There would be mutually exclusive crate features (likely u8, u16, u32, usize), but that's not an issue because they would only be selected by the crate that provides the interrupt-free operation, and there can only be one of those anyway.

**Comment by Dirbaio** [comment]
Agreed!

It seems xtensa (esp32, esp8266) also requires an u32 token: https://github.com/esp-rs/xtensa-lx/blob/25118592bf536886fce722dc3af126d6e38295aa/src/interrupt.rs#L30

I wonder if it should be a newtype instead of a type alias, so user crates don't end up accidentally depending on it being a particular type. That'd be a breaking change though.

**Comment by reitermarkus** [comment]
> I wonder if it should be a newtype instead of a type alias

I think it should. Also makes the API a bit more readable than using a bare integer type.
